- name: Restart SSH
  service:
    name: ssh
    state: restarted

- name: Restart Apache
  service:
    name: apache2
    state: restarted

- name: Restart MySQL
  service:
    name: mysql
    state: restarted

- name: Restart PostgreSQL
  service:
    name: postgresql
    state: restarted
